[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gds2palace"
dynamic = ["version"]
description = "Create AWS Palace model from RFIC GDSII layout file"
authors = [
    { name = "Volker Muehlhaus", email = "volker@muehlhaus.com" }
]
license = "GPL-3.0-or-later"
readme = "README_pypi.md"
requires-python = ">=3.9"
dependencies = [
    "gdspy>1.6.0",
    "gmsh",
    "numpy",
]

[project.urls]
Homepage = "https://github.com/VolkerMuehlhaus/gds2palace_ihp_sg13g2"
Repository = "https://github.com/VolkerMuehlhaus/gds2palace_ihp_sg13g2"
Changelog = "https://github.com/VolkerMuehlhaus/gds2palace_ihp_sg13g2/blob/main/doc/CHANGES.md"

[tool.setuptools.dynamic]
version = {attr = "gds2palace.__version__"}

[tool.setuptools.packages.find]
where = ["workflow"]
include = ["gds2palace*"]
